; Script generated by Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Smart Shop"
#define MyAppVersion "1.0"
#define MyAppPublisher "EagleShadow Technology"
#define MyAppURL "https://eagleshadow.technology/"
#define MyAppExeName "SmartShopLauncher.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A1B2C3D4-E5F6-7890-1234-567890ABCDEF}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
; Remove the following line to run in administrative mode (install for all users.)
PrivilegesRequired=lowest
OutputDir=..\dist_installer
OutputBaseFilename=SmartShop_Installer
SetupIconFile=..\src\img\favicon.ico
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
DisableProgramGroupPage=yes
; Security: Prevents users from installing in a protected folder without admin rights, ensuring stability
PrivilegesRequiredOverridesAllowed=dialog

[Languages]
; English as default, you can add Arabic if you download Arabic.isl
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; IMPORTANT: We assume the user has run 'build_app.bat' and 'tools/clean_bin.bat' before this.
; The source directory is the 'dist' folder generated by the build script.

; FAIL-SAFE: Explicitly check for the main executable first. 
; If this file is missing in 'dist', the Inno Setup Compiler will stop with an error here.
Source: "..\dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion

; Copy all other files
Source: "..\dist\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
; Run the VCRedist installer if needed (optional - you can bundle it in dist/redist)
; Filename: "{app}\redist\vc_redist.x64.exe"; Parameters: "/install /quiet /norestart"; Check: VCRedistNeedsInstall; StatusMsg: "Installing Visual C++ Redistributable..."

Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#MyAppName}}"; Flags: nowait postinstall skipifsilent

[Code]
// Helper function to check if VC++ Redist is needed (simplified)
function VCRedistNeedsInstall: Boolean;
begin
  // Check registry for VC++ 2015-2022
  // This is just a placeholder logic. Real checking is more complex.
  Result := False; 
end;

[Dirs]
; Ensure the data directory exists in AppData (handled by the Launcher code actually, but good to know)
; The application saves data to %APPDATA%\SmartShop\data, so we don't need to create it here.
; However, if we need a specific folder in {app} to be writable by non-admin users (e.g. logs), we can set permissions.
Name: "{app}\logs"; Permissions: users-modify
